[pytest]
# Подбираем только .py-файлы, начинающиеся с test_
python_files = test_*.py

# Игнорируем указанные директории
norecursedirs = build dist

# Дополнительные опции
addopts =
    --ignore-glob=*.txt
    --ignore-glob=*.md
    

# Фильтруем предупреждения
filterwarnings =
    ignore::DeprecationWarning
    ignore::DeprecationWarning:click

